algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações
var
salario:real
salariocomaumento:real
nome:caractere
inicio

Escreva ("Olá, por favor informe seu nome: ")

leia(nome)

escreva ("Digite o salario que voce quer ver o aumento de 30%")

leia (salario)

salariocomaumento <- salario*30/100

salariocomaumento <- salariocomaumento+salario

escreva ("O seu salário com o aumento de 30% é:", salariocomaumento)

fimalgoritmo
