algoritmo "semnome"
// Função :
// Autor :
// Data : 22/02/2022
// Seção de Declarações
var

celsius , farenheit  : real

inicio

escreval("Farenheit")
leia(farenheit)
celsius <- (farenheit-32)*5/9
escreval("celsius = ", celsius)
Se celsius <= 15 entao
   escreval ("Está frio")
   senao
   se celsius <= 28 entao
      escreval ("Esta calor")
      senao
      escreval ("Esta agradável")
      fimse
   fimse
          


   fimalgoritmo
